// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXk0EaknJKEDv_PN9GiODFCYOh71XnFWk',
    appId: '1:195987110501:web:a8aab7c069693e70d0a48c',
    messagingSenderId: '195987110501',
    projectId: 'foster-care-ca8d2',
    authDomain: 'foster-care-ca8d2.firebaseapp.com',
    storageBucket: 'foster-care-ca8d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVh9eGQKczBMHeUfEWIfWbTkraZ-Klog8',
    appId: '1:195987110501:android:af03e94294bb86c6d0a48c',
    messagingSenderId: '195987110501',
    projectId: 'foster-care-ca8d2',
    storageBucket: 'foster-care-ca8d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dlOSGs_APbLpm9Pm5xrWax51yXMxUw0',
    appId: '1:195987110501:ios:5e73f78bbaba7b3cd0a48c',
    messagingSenderId: '195987110501',
    projectId: 'foster-care-ca8d2',
    storageBucket: 'foster-care-ca8d2.appspot.com',
    iosBundleId: 'com.example.flutterApplicationUee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0dlOSGs_APbLpm9Pm5xrWax51yXMxUw0',
    appId: '1:195987110501:ios:90428ca42c4505cfd0a48c',
    messagingSenderId: '195987110501',
    projectId: 'foster-care-ca8d2',
    storageBucket: 'foster-care-ca8d2.appspot.com',
    iosBundleId: 'com.example.flutterApplicationUee.RunnerTests',
  );
}
